Data model processing
principlebrothers/CosmosExpress pull request #2
Opened 2022-11-24 22:05 UTC by principlebrothers

## Complete milestone 2
In this milestone I achieved the following;
- [x] Create model
- [x] Use model to insert data
- [x] Create custom methods

2022-11-25 01:08 UTC, AnselemOdims requested changes
### Hi @principlebrothers, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-25 01:08 UTC, AnselemOdims commented on app/models/user.rb
> +  has_many :likes
- [ ] Please kindly include the foreign key for each of the associations.

Hint:
`has_many :posts, foreign_key: 'author_id'`

2022-11-25 01:08 UTC, AnselemOdims commented on app/models/post.rb
> +  end
- [ ] The recent comments should be 5 and not 3. Please kindly ensure the right limit is implemented

2022-11-25 01:30 UTC, principlebrothers commented on app/models/post.rb
> +  end
@AnselemOdims I appreciate the review.

2022-11-25 01:32 UTC, principlebrothers commented on app/models/user.rb
> +  has_many :likes
Hi @AnselemOdims, can you please explain to me why I must use the him provided. I appreciate a recorded video link. I want to understand what I am doing. Thank you

2022-11-25 02:05 UTC, Reem-lab approved these changes
# Hi @principlebrothers, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights
- No Linters error ✅
- Followed Git flow ✅
- Great working on the functionality 🔥🚀🎉

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 02:05 UTC, Reem-lab commented on app/models/post.rb
> +  end
- [ OPTIONAL ] I think it would be great if you make the method private thata's very good when you want to follow best practices for access controls and abstraction for classes 🔥🚀💯✨✅

2022-11-25 10:42 UTC, principlebrothers commented on app/models/post.rb
> +  end
Hello @Reem-lab Thanks for the view. Please I need help with specific documentation for your suggestion. That will help as a point of reference for me. Thank you

2022-11-25 10:43 UTC, merged

2022-12-02 16:34 UTC, Reem-lab commented on app/models/post.rb
> +  end
Hello @principlebrothers you can contact with me through slack if you need ny help ❤