Device
principlebrothers/CosmosExpress pull request #9
Opened 2022-12-08 11:31 UTC by principlebrothers

## Complete milestone 9
In this milestone, I achieved the following
- [x] Install and setup devise so it 

    - Can register a new user.
    - User logs in with a combination of email and password.
    - Stores hashed password in the database.
    - Ask for confirmation of email.
    - Can reset password.

2022-12-08 12:15 UTC, Nemwel-Boniface requested changes
## Hello @principlebrothers  and @username-forGithub      :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job working on your project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 12:15 UTC, Nemwel-Boniface commented on app/views/devise/registrations/new.html.erb
> +<%= form_with(resource, as: resource_name, url: registration_path(resource_name), class: "container") do |f| %>
- [ ] When I click on the signup burron, I am receiving this error. Kindly look into why this is the case.

![image](https://user-images.githubusercontent.com/86318284/206441357-ed7e871e-1d45-466b-9e94-1ec95575a7cb.png)

2022-12-08 15:59 UTC, principlebrothers commented on app/views/devise/registrations/new.html.erb
> +<%= form_with(resource, as: resource_name, url: registration_path(resource_name), class: "container") do |f| %>
Thanks for the feedback @Nemwel-Boniface. The error has been fixed now

2022-12-08 16:19 UTC, omarsalem7 commented on app/views/layouts/application.html.erb
> +          <%= link_to "Sign Out", destroy_user_session_path(current_user), method: :delete, class: "btn btn-outline-danger" %>
- [ ] [OPTIONAL] When I click on `sign out, I got the following error
>![image](https://user-images.githubusercontent.com/53402600/206503163-78895e9b-d9d9-42f9-812b-0aa3fbe3371c.png)

2022-12-08 16:23 UTC, principlebrothers commented on app/views/layouts/application.html.erb
> +          <%= link_to "Sign Out", destroy_user_session_path(current_user), method: :delete, class: "btn btn-outline-danger" %>
@omarsalem7, I appreciate you feedback. I will need your assistance this since I have been about it since morning. I will appreciate more if you provide suggestion on how to go about it. Thank you

2022-12-08 18:38 UTC, principlebrothers commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
When I add the confirmable and I signed up, it brings [this interface](https://user-images.githubusercontent.com/92553079/206537934-57e3435e-327e-486e-9579-4f352dc2deb6.png) to confirm the email. When I check the console it has the information yet the [interface](https://user-images.githubusercontent.com/92553079/206537934-57e3435e-327e-486e-9579-4f352dc2deb6.png) remains still with no error message. **Kindly assist me to fix the unchanged interface. Thank you**

2022-12-09 08:56 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @principlebrothers ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

- [ ] Kindly fix the broken MIT license link to make your readme file more professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 08:59 UTC, principlebrothers commented
I appreciate the review, @1GORDON.

2022-12-09 08:59 UTC, merged